Update build.yml
update logging

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,6 +27,12 @@ jobs:
     - name: Install dependencies
       run: npm install
 
+    - name: List node_modules contents
+      run: ls -la node_modules
+
+    - name: Ensure build directory exists
+      run: mkdir -p dist
+
     - name: Build for ${{ matrix.platform }}
       run: npm run dist -- --linux --win --mac
       if: matrix.platform == 'all'
@@ -37,7 +43,13 @@ jobs:
       run: npm run dist -- --${{ matrix.platform }}
       env:
         CI: true
-
+        
+    - name: Check if build directory exists
+      run: |
+        if [ ! -d "dist" ]; then
+        echo "Error: dist directory not found."
+        exit 1
+        fi
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
       with:
