Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -35,51 +35,45 @@ jobs:
       run: |
         sudo apt-get update
         sudo apt-get install -y build-essential
-        
+
     - name: Install dependencies
       run: npm install --no-cache --verbose --force --no-audit
-
-    - name: List node_modules contents
-      run: ls -la node_modules/http-proxy-agent
-
-    - name: Install http-proxy-agent and agent-base again
-      run: npm install http-proxy-agent@latest agent-base@latest
-
-    - name: List node_modules contents again
-      run: ls -la node_modules/http-proxy-agent
-      
-    - name: Print Node.js version
-      run: node -v
-
-    - name: Print npm version
-      run: npm -v
-
-    - name: List installed packages
-      run: npm ls --depth=0
 
     - name: Ensure build directory exists
       run: mkdir -p dist
 
     - name: Build for ${{ matrix.platform }}
-      run: npm run dist -- --linux --win --mac
-      if: matrix.platform == 'all'
-      env:
-        CI: true
-
-    - name: Build for ${{ matrix.platform }}
-      run: npm run dist -- --${{ matrix.platform }}
+      run: |
+        if [ "${{ matrix.platform }}" == "linux" ]; then
+          npm run dist -- --linux
+        elif [ "${{ matrix.platform }}" == "win32" ]; then
+          npm run dist -- --win
+        elif [ "${{ matrix.platform }}" == "darwin" ]; then
+          npm run dist -- --mac
+        else
+          echo "Unsupported platform: ${{ matrix.platform }}"
+          exit 1
+        fi
       env:
         CI: true
         
     - name: Check if build directory exists
       run: |
         if [ ! -d "dist" ]; then
-        echo "Error: dist directory not found."
-        exit 1
+          echo "Error: dist directory not found."
+          exit 1
         fi
+
+    - name: Get version from package.json
+      id: get_version
+      run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV || { echo "Failed to get version from package.json"; exit 1; }
+
     - name: Upload artifacts
       uses: actions/upload-artifact@v4
       with:
-        name: electron-app-${{ matrix.platform }}
-        path: dist
-
+        name: electron-app-${{ env.VERSION }}-${{ matrix.platform }}
+        path: |
+          dist/QuickAi_${{ env.VERSION }}_amd64.deb
+          dist/QuickAi_${{ env.VERSION }}_amd64.exe
+          dist/QuickAi_${{ env.VERSION }}_amd64.AppImage
+        if-no-files-found: error
